### ISSUE TITLE
Initiating conversation

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/promobot-example#1]
Does the user always need to send the first message? Is there a way to display a message telling them to do that?

**Comment by walkah** [comment]
I have the conversation triggering on "facebook_optin" which should get fired when someone (who isn't a page admin) first adds the bot. 

The other option that might be worth implementing would be to add a permanent menu option (which is a thing FB bots support) for "Start Demo" ... I've created an issue for that in #4
