### ISSUE TITLE
Show more info about how it works behind the scenes?

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/promobot-example#2]
What do you think of being able to tell the bot to go into verbose mode where the bot tells the user about the call it's making to our API?

**Comment by walkah** [comment]
Right now there's just the single `evaluate` call. I think it makes sense to just always report what happened - sound good?

**Comment by mattfogel** [comment]
Yup! Sounds good to me. What format do you think would be interesting to devs? Something like this maybe?

"Calling Fuzzy.ai API with the following inputs: x = 1, y = 15, etc."

"Fuzzy.ai API returns X as recommended discount"

**Comment by walkah** [comment]
Yeah. That looks good. Mentioning that we convert text values to integer / numeric equivalents would be important.
